@startuml

actor "Benutzer des Frames: \n  SortierAlgorithmen" as frameUser

package Frame {

usecase "Sortieralgorithmus \n ""Bubbelsort"" \n ausführen" as UC_BubbelSort

usecase include_at_UC_BubbelSort as "
Per ""WaitCursor"" dem Nutzer die Ausführung ankündigen.
----
tempArray benutzen
----
Zeitmessung durchführen für Bubbelsort-Algorithmus.
----
tempArray anzeigen in Widget ""lwKopie"".
----
Per ""ArrowCursor"" dem Nutzer die Beendigung der Ausführung ankündigen.
"
UC_BubbelSort .> include_at_UC_BubbelSort : <<include>>
frameUser .. UC_BubbelSort
left to right direction


note right of include_at_UC_BubbelSort
Test
end note
@enduml
